SEARCH_DIR("/usr/lib/x86_64-linux-gnu/")
SEARCH_DIR("/lib64/")
SEARCH_DIR("/lib/")
SEARCH_DIR("/usr/lib/")
SEARCH_DIR("/usr/lib/gcc/x86_64-linux-gnu/9/")
SEARCH_DIR("/home/gigauser/Development/Pascal/Projects/Tiny/src/")
SEARCH_DIR("./")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/httpd22/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/sqlite/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/libenet/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/imlib/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/libmagic/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/mad/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/pxlib/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/libgc/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-image/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/aspell/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/graph/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/bzip2/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/ptc/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/oracle/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/gmp/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-sound/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/libgd/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/libpng/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/modplug/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/paszlib/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/gdbm/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/webidl/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-xml/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/opengles/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/pcap/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl-generics/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/libtar/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/uuid/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/syslog/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-passrc/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/libfontconfig/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-net/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/opencl/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/ldap/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fftw/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/gdbint/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/hash/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fpindexer/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/libcurl/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/hermes/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/gtk1/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/sdl/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/libcups/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/imagemagick/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/cairo/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/pthreads/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/opengl/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-fpcunit/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/dblib/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-report/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl-console/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/oggvorbis/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/chm/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-base/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/openal/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fpmkunit/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/utils-pas2js/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/numlib/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-registry/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/zlib/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fv/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-pdf/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-web/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/dts/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-stl/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/pasjpeg/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/ncurses/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-process/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/lua/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-sdo/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/xforms/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl-objpas/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl-unicode/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/libvlc/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/cdrom/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/iconvenc/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/mysql/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/bfd/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/a52/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fppkg/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/utmp/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/tcl/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/gnome1/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/odata/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/httpd24/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/libxml2/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-extra/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fastcgi/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-js/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/googleapi/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/svgalib/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-res/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/pastojs/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/jni/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/gtk2/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-db/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/ibase/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/zorba/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/vcl-compat/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/libsee/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/x11/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/users/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/regexpr/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/ggi/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/gnutls/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/symbolic/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rsvg/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl-extra/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/utils-lexyacc/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/libusb/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/postgres/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/libffi/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-json/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/proj4/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/dbus/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/libmicrohttpd/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fpgtk/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/openssl/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/newt/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/unzip/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/fcl-async/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/odbc/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/")
SEARCH_DIR("/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/")
INPUT(
/usr/lib/x86_64-linux-gnu/crti.o
/usr/lib/gcc/x86_64-linux-gnu/9/crtbeginS.o
/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl/si_c.o
/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl/abitag.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/playground.o
/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl/system.o
/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl/objpas.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/tiny.system.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/tiny.graphics.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/tiny.application.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/tiny.physics.scene.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/play.svg.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/play.svgrender.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/play.drawphysics.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/play.svgscene.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/play.svggrid.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/play.svgphysics.o
/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl/cthreads.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/tiny.types.o
/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl/linux.o
/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl/baseunix.o
/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl/unix.o
/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl/unixtype.o
/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl/initc.o
/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl/dl.o
/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl/unixutil.o
/home/gigauser/Development/Pascal/fpc/lib/fpc/3.3.1/units/x86_64-linux/rtl/ctypes.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/tiny.interop.unix.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/tiny.interop.sdl2.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/tiny.interop.nanovg.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/tiny.interop.gl.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/tiny.widgets.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/tiny.widgets.themes.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/tiny.physics.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/tiny.interop.chipmunk2d.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/tiny.text.xml.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/tiny.interop.unix.xml2.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/tiny.widgets.custom.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/tiny.animation.o
/home/gigauser/Development/Pascal/Projects/Tiny/playground/lib/x86_64-linux/tiny.geometry.o
)
GROUP(
../libs/libnanovg-gl3-linux.a
)
INPUT(
-lm
-lpthread
-ldl
-lSDL2
-l../libs/chipmunk-linux
-lxml2
)
GROUP(
-lc
)
INPUT(
/usr/lib/gcc/x86_64-linux-gnu/9/crtendS.o
/usr/lib/x86_64-linux-gnu/crtn.o
)
SECTIONS
{
  .fpcdata           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
  .threadvar : { *(.threadvar .threadvar.* .gnu.linkonce.tv.*) }
}
INSERT AFTER .data;
